### PR TITLE
Create decimal.c

### PR DESCRIPTION
**Pull request by AviParmar**

### CODE REVIEW

**Comment by ayuushhh** [comment]
Im merging this...let me know if this pr counts in your hactoberfest challenge

**Comment by AviParmar** [comment]
It is not merged and pr is not counting

**Comment by ayuushhh** [comment]
actually i have merged it, but maybe my repo is not eligible for hactoberfest .They have made the rules stricter .Is it showing '!'  in hactoberfest?

**Comment by AviParmar** [comment]
Yes they are showing that the maintainer repository is not not
participating in hactoberfest. They can participate in hactoberfest by
putting label on it .
🙏 Please acknowledge because only 1 pull request is remaining to complete
for me please help mein complete the challenge .It is humble request

**Comment by ayuushhh** [comment]
actually they have made the rules stricter. otherwise i have marked my repo for hactoberfest and your pr too. i made this repo yesterday itself. So try after few days and make another pr and lets see what happens

**Pull request merged**
